fragment FrontPageResultPartial on FrontPage {
  uid
  publicationDate
  content {
    uid
    component {
      name
      configuration {
        h
        w
        type
      }
    }
    postUid
    post {
      uid
      previewUrl
      title
      createdAt
    }
    position {
      x
      y
    }
  }
}
