query GetPost($uid: UID!) {
  post(uid: $uid) {
    uid
    title
    description
    previewUrl
    content
    tags {
      name
    }
    githubAuthor {
      uid
      name
      usernameUrl
      avatarUrl
    }
    createdAt
    comments {
      uid
      author {
        uid
        avatarUrl
        publicName
      }
      replyingToComment {
        uid
        content
      }
      content
      createdAt
    }
  }
}
