export * from './__generated__/GetPost'
export * from './__generated__/PostsByFeed'
export * from './__generated__/PostsByRecommendation'
export { default as GetPostQuery } from './GetPost.gql'
export { default as PostsByFeedQuery } from './PostsByFeed.gql'
export { default as PostsByRecommendation } from './PostsByRecommendation.gql'
