query PostsByFeed($uid: UID!, $page: Int, $perPage: Int) {
  postsByFeed(uid: $uid, page: $page, perPage: $perPage) {
    items {
      uid,
      title,
      previewUrl,
      createdAt
    }
  }
}
