import { PostCard } from 'entities/posts'
import { mockPosts } from 'entities/posts/mockPosts'
import type { NextPage } from 'next'
import { GetStaticProps } from 'next'
import Head from 'next/head'
import React from 'react'
import type { Post } from 'shared/api/types'
import { Grid } from 'shared/ui/grid'
import { Header } from 'shared/ui/header'
import { Layout } from 'shared/ui/layout'

type Props = {
    posts: Post[]
}

const Home: NextPage<Props> = ({ posts }) => (
    <>
        <Head>
            <title> Raz media main page</title>
            <meta content='Generated by create next app' name='description' />
            <link href='/favicon.ico' rel='icon' />
        </Head>

        <Layout>
            <Header />
            <Grid>
                {posts.map((post) => (
                    <PostCard key={post.uid} {...post} />
                ))}
            </Grid>
        </Layout>
    </>
)

export const getStaticProps: GetStaticProps = async () => {
    const res = await fetch(
        'https://raz-backoffice-api-dev.herokuapp.com/posts/',
    )
    const posts = await res.json()
    return { props: { posts: mockPosts } }
}
export default Home
