import { getDataFromTree } from '@apollo/client/react/ssr'
import { useGetLatestPosts } from 'entities/posts/model/__generated__/GetLatestPosts'
import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { withApollo } from 'shared/lib'
import { Header } from 'shared/ui/header'
import { Layout } from 'shared/ui/layout'

const Home: NextPage = () => {
  const { data } = useGetLatestPosts()

  return (
    <>
      <Head>
        <title> Raz media main page</title>
        <meta content='Generated by create next app' name='description' />
        <link href='/favicon.ico' rel='icon' />
      </Head>

      <Layout>
        <Header />
      </Layout>
    </>
  )
}

export default withApollo(Home, { getDataFromTree })
