import type { NextPage } from 'next'
import Head from 'next/head'
import React from 'react'
import { Header } from 'shared/ui/header'
import { Layout } from 'shared/ui/layout'
import { MARKDOWN_MOCK, MarkdownRenderer } from 'shared/ui/markdown-renderer'

type HomePageProps = {
  content: string
}

const HomePage: NextPage<HomePageProps> = ({ content }) => (
  <>
    <Head>
      <title> Raz media main page</title>
      <meta content='Generated by create next app' name='description' />
      <link href='/favicon.ico' rel='icon' />
    </Head>

    <Layout>
      <Header />
      ✨✨✨✨
      <MarkdownRenderer>{content}</MarkdownRenderer>
    </Layout>
  </>
)

export async function getServerSideProps() {
  return { props: { content: MARKDOWN_MOCK } }
}

export default HomePage
