query CurrentFrontPage {
  currentFrontPage {
    uid
    publicationDate
    content {
      uid
      component {
        name
        configuration {
          h
          w
          type
        }
      }
      postUid
      post {
        uid
        tags {
          description
          name
        }
        readingTime
        previewUrl
        title
        content
        description
        createdAt
      }
      position {
        x
        y
      }
    }
  }
}
