name: "ESLint Check"
on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-lint:
    name: Test Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Perform ESLint Check
        run: yarn lint
